apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app-frontend
  labels:
    app: my-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
        tier: frontend
    spec:
      volumes:
        - name: nginx-sites-conf
          configMap:
            name: nginx-sites-conf
      containers:
      - image: w1nsun/mynginx:1.0
        imagePullPolicy: Always
        name: my-app
        ports:
        - name: http-server
          containerPort: 80
        volumeMounts:
          - name: nginx-sites-conf
            mountPath: /etc/nginx/conf.d/
      - image: w1nsun/myphp:1.0
        imagePullPolicy: Always
        name: my-app-fpm
        ports:
        - name: fpm-sock
          containerPort: 9000
